### ISSUE TITLE
Redundant first link on RH TOC

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/docs-portal-onboarding-guide#12]
The first link in the right pane (table of contents) is a redundant link to the same main doc page. Please remove that first link.

![image](https://user-images.githubusercontent.com/730187/97052419-96fd2a80-1546-11eb-8640-204bf43139e0.png)

**Comment by Sterling463** [comment]
This looks a quirk of how the publishing system works. Removing this link confuses the toc.

**Comment by robb-romans** [comment]
Thanks
