### ISSUE TITLE
Broken link to the Rackspace Technology Customer Portal

### ISSUE THREAD

**Issue by robb-romans** [rackerlabs/docs-portal-onboarding-guide#13]
On this page:
https://docs.rackspace.com/docs/portal-onboarding-guide/intended_audience/
broken link to  `the the Rackspace Technology Customer Portal`
redundant the the

link entitled `refer to the relevant documentation on the Rackspace Technology Support site .`
link goes to developer site not support site

extra spaces between link and period

**Comment by Sterling463** [comment]
creating PR to fix

**Comment by ravivalluri** [comment]
Fixed.
